### ISSUE TITLE
Error with using template via GitHub API

### ISSUE THREAD

**Issue by dnoneill** [minicomp/wax#128]
Hi,
I tried to create an copy using the template via API and I got the following error: 

{'message': 'Although you appear to have the correct authorization credentials, the `minicomp` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/', 'documentation_url': 'https://docs.github.com/rest/reference/repos#create-a-repository-using-a-template'}

Anyway I can get added so I can create a new repo using the API?

**Comment by bmschmidt** [comment]
I am not a maintainer so feel free to ignore me, but can I ask API you want to use here and why?

The normal course would be to click the 'use this template' button on the repo to create your own fork in github; or if scripting, you can just download the zipfile at https://github.com/minicomp/wax/archive/refs/heads/main.zip and work from that.

**Comment by dnoneill** [comment]
I have an application I have created called Annonatate (https://annonatate.herokuapp.com). I am working on integrating it with Wax. I would like for users to be able create a copy of the repo via my application. I have also gotten it so users don't have to do all the scripting via the command line, but instead can upload a csv and the application will do the production of the derivatives for them. I am hoping to take some of the burden away from users with the application, we have some professors who Wax would be a good tool, but right now it is far too much work with their lack of technical expertise. I am hoping I have these new changes out in the next week but all of the wax integration with Annonatate is still only local.
