### ISSUE TITLE
Images not generating 

### ISSUE THREAD

**Issue by vzafrin** [minicomp/wax#13]
Hello! I run the server, which gives me no errors; but when I load the localhost:4000/wax/ site, I get a string of errors and no images in the IIIF viewer or the gallery below. The errors are as follows:

[2018-10-05 09:45:26] ERROR `/wax/iiif/qatar/images/obj6-1/full/1140,/0/default.jpg' not found.
[2018-10-05 09:45:26] ERROR `/wax/iiif/qatar/images/obj10-1/full/1140,/0/default.jpg' not found.
[2018-10-05 09:45:26] ERROR `/wax/iiif/qatar/images/obj7-1/full/1140,/0/default.jpg' not found.
[2018-10-05 09:45:26] ERROR `/wax/iiif/qatar/images/obj1-1/full/1140,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj6-1/full/1140,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj10-1/full/1140,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj1-1/full/1140,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj1-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj2-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj5-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj3-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj4-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj7-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj6-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj8-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj10-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj9-1/full/250,/0/default.jpg' not found.
[2018-10-05 09:45:27] ERROR `/wax/iiif/qatar/images/obj11-1/full/250,/0/default.jpg' not found.

I note that every object in wax/src/_data/iiif/qatar appears in the above errors (in a modified form) at least once, but several of them appear more than once. 

I tried following the directions here: https://minicomp.github.io/wiki/#/wax/guides/tasks?id=top and ran into two problems. One, I don't have a wax_tasks directory. Two, I don't have a _qatar directory, but did rm -rf src/_data/iiif. Three, I tried `bundle exec rake wax:pagemaster qatar`, got an error. Here's the full error with `--trace`:

rake aborted!
Don't know how to build task 'wax:pagemaster' (see --tasks)
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task_manager.rb:59:in `[]'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:159:in `invoke_task'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<top (required)>'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/cli/exec.rb:75:in `load'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/cli/exec.rb:75:in `kernel_load'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/cli.rb:424:in `exec'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/cli.rb:18:in `start'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/usr/local/bin/bundle:22:in `<main>'

What do I do now? Should I have Ruby knowledge at this point that I don't have?

**Comment by mnyrop** [comment]
Hi @vzafrin, do you have a repository you're working on that I can look at to help troubleshoot?

**Comment by vzafrin** [comment]
@mnyrop I was using the quick start directions https://minicomp.github.io/wiki/#/wax/ (which really turned into a dozen other installs, including ImageMagick and a bunch of brew/ruby/etc updates). It directs me to clone https://github.com/minicomp/wax.git.

I also checked out https://minicomp.github.io/wiki/#/wax/guides/setup?id=top and got no significant errors  until I ran the server locally as above. 

I'm doing this on Mac OS running High Sierra.

**Comment by mnyrop** [comment]
Can you copy the contents of your `Rakefile` in a comment?

**Comment by vzafrin** [comment]
I know! I'm just Very Excited about it. Thank you for your help.

Rakefile:

spec = Gem::Specification.find_by_name 'wax_tasks'
Dir.glob("#{spec.gem_dir}/lib/tasks/*.rake").each {|r| load r}

`bundle show`:

Gems included by the bundle:
  * activesupport (5.2.0)
  * addressable (2.5.2)
  * archive-zip (0.11.0)
  * bundler (1.16.1)
  * capybara (3.3.1)
  * childprocess (0.9.0)
  * chromedriver-helper (1.2.0)
  * colorator (1.1.0)
  * colorize (0.8.1)
  * concurrent-ruby (1.0.5)
  * diff-lcs (1.3)
  * em-websocket (0.5.1)
  * ethon (0.11.0)
  * eventmachine (1.2.7)
  * ffi (1.9.25)
  * forwardable-extended (2.6.0)
  * html-proofer (3.9.1)
  * http_parser.rb (0.6.0)
  * i18n (0.9.5)
  * io-like (0.3.0)
  * jekyll (3.8.3)
  * jekyll-sass-converter (1.5.2)
  * jekyll-watch (2.0.0)
  * kramdown (1.17.0)
  * liquid (4.0.0)
  * listen (3.1.5)
  * mercenary (0.3.6)
  * mini_magick (4.8.0)
  * mini_mime (1.0.0)
  * mini_portile2 (2.3.0)
  * minitest (5.11.3)
  * nokogiri (1.8.3)
  * parallel (1.12.1)
  * pathutil (0.16.1)
  * public_suffix (3.0.2)
  * rack (1.6.10)
  * rack-jekyll (0.5.0)
  * rack-test (1.0.0)
  * rake (12.3.1)
  * rb-fsevent (0.10.3)
  * rb-inotify (0.9.10)
  * rouge (3.1.1)
  * rspec (3.7.0)
  * rspec-core (3.7.1)
  * rspec-expectations (3.7.0)
  * rspec-mocks (3.7.0)
  * rspec-support (3.7.1)
  * ruby_dep (1.5.0)
  * rubyzip (1.2.1)
  * safe_yaml (1.0.4)
  * sass (3.5.6)
  * sass-listen (4.0.0)
  * selenium-webdriver (3.12.0)
  * thread_safe (0.3.6)
  * typhoeus (1.3.0)
  * tzinfo (1.2.5)
  * wax_iiif (0.0.2)
  * wax_tasks (0.3.0 893e6ce)
  * xpath (3.1.0)
  * yell (2.0.7)

**Comment by mnyrop** [comment]
okay, can you run:

```
bundle update
```
then
```
bundle exec rake --tasks
```
and copy the results?

**Comment by vzafrin** [comment]
`bundle update` returns:

Fetching https://github.com/mnyrop/wax_tasks.git
fatal: Needed a single revision
Revision beta does not exist in the repository https://github.com/mnyrop/wax_tasks.git. Maybe you misspelled it?

**Comment by mnyrop** [comment]
Ah I think I see the problem. 

Delete the contents of your Gemfile and replace it with:

```
source 'https://rubygems.org'
gem 'jekyll', '~> 3.8.3'

group :development, :test do
  gem 'rspec'
  gem 'selenium-webdriver', '3.12.0'
  gem 'chromedriver-helper'
  gem 'capybara'
  gem 'rack-jekyll'
  gem 'wax_tasks'
end
```

The newer version of wax_tasks should work without needing to reference the Git repo.

Then try 
`bundle install`

and 

`bundle exec rake --tasks`

 and copy the results

**Comment by vzafrin** [comment]
OK, here's the output of `bundle install`:

Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.1
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.1 (was 5.2.0)
Using public_suffix 3.0.2
Using addressable 2.5.2
Using io-like 0.3.0
Using archive-zip 0.11.0
Using bundler 1.16.1
Using mini_mime 1.0.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.3
Using rack 1.6.10
Using rack-test 1.0.0
Using xpath 3.1.0
Using capybara 3.3.1
Using ffi 1.9.25
Using childprocess 0.9.0
Using chromedriver-helper 1.2.0
Using colorator 1.1.0
Using colorize 0.8.1
Using diff-lcs 1.3
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using ethon 0.11.0
Using forwardable-extended 2.6.0
Using mercenary 0.3.6
Using parallel 1.12.1
Using typhoeus 1.3.0
Using yell 2.0.7
Fetching html-proofer 3.9.2 (was 3.9.1)
Installing html-proofer 3.9.2 (was 3.9.1)
Using rb-fsevent 0.10.3
Using rb-inotify 0.9.10
Using sass-listen 4.0.0
Using sass 3.5.6
Using jekyll-sass-converter 1.5.2
Using ruby_dep 1.5.0
Using listen 3.1.5
Using jekyll-watch 2.0.0
Using kramdown 1.17.0
Using liquid 4.0.0
Using pathutil 0.16.1
Using rouge 3.1.1
Using safe_yaml 1.0.4
Using jekyll 3.8.3
Fetching mini_magick 4.9.2 (was 4.8.0)
Installing mini_magick 4.9.2 (was 4.8.0)
Using rack-jekyll 0.5.0
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using rubyzip 1.2.1
Using selenium-webdriver 3.12.0
Using wax_iiif 0.0.2
Fetching wax_tasks 0.3.2 (was 0.3.0)
Installing wax_tasks 0.3.2 (was 0.3.0)
Bundle complete! 7 Gemfile dependencies, 60 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

And `bundle exec rake --tasks`:

rake wax:iiif        # generate iiif derivatives from local image files
rake wax:jspackage   # write a simple package.json for monitoring js dependencies
rake wax:lunr        # build lunr search index (with default UI if UI=true)
rake wax:pagemaster  # generate collection md pages from yaml or csv data source
rake wax:push        # push compiled Jekyll site to git branch BRANCH
rake wax:test        # run htmlproofer, rspec if .rspec file exists

The images are still not showing up.

**Comment by mnyrop** [comment]
That was just to fix the tasks, and it looks like it was successful. You should now be able to run them like normal, including 

`bundle exec rake wax:pagemaster qatar` to generate the item pages, and 

`bundle exec rake wax:iiif qatar` to generate the IIIF images if you are still using the sample data.

To explain a bit: in the version of Wax you cloned, I purposefully didin't include the pages and images to encourage users to run the tasks above and generate them themselves.

The documentation should be updated to reflect this later today/early tomorrow.

I included the images and pages In the current version, however, to help folks get started more quickly.  If you have Ruby and ImageMagick installed, you should be able to re-clone this repository and just run `bundle` and `bundle exec jekyll serve` without first needing to run the `wax_tasks` tasks.

**Comment by vzafrin** [comment]
Thanks, @mnyrop. I see that you did update the documentation. At `bundle exec rake wax:iiif qatar` I get:

rake aborted!
NameError: uninitialized constant WaxTasks::Error::MissingIiifSrc
Did you mean?  WaxTasks::Error::MissingPid
/usr/local/lib/ruby/gems/2.5.0/gems/wax_tasks-0.3.2/lib/wax_tasks/iiif_collection.rb:34:in `process'
/usr/local/lib/ruby/gems/2.5.0/gems/wax_tasks-0.3.2/lib/wax_tasks/task_runner.rb:97:in `block in iiif'
/usr/local/lib/ruby/gems/2.5.0/gems/wax_tasks-0.3.2/lib/wax_tasks/task_runner.rb:96:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/wax_tasks-0.3.2/lib/wax_tasks/task_runner.rb:96:in `iiif'
/usr/local/lib/ruby/gems/2.5.0/gems/wax_tasks-0.3.2/lib/tasks/iiif.rake:9:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => wax:iiif
(See full trace by running task with --trace)

**Comment by mnyrop** [comment]
Hi @vzafrin, are you processing the test data or trying to use your own? This error means that wax_tasks can't find the source images, which it expects to exists in `_data/iiif/{name_of_collection}`, for the `qatar` collection this is `_data/iiif/qatar`.

Is there any way you can push the repository to your github account? I can help if I can see what you're working with, but I can't do much without looking.

**Comment by vzafrin** [comment]
@mnyrop, I was processing the test data — and that was the last bit of what I needed! I downloaded another copy of `_data`, with `iiif/qatar` in it, and re-ran `bundle exec rake wax:iiif qatar`. It worked, though much more slowly than I'd expected. Now the site loads with images. NOW I can start figuring out how to build my own collection. Thank you!
