### ISSUE TITLE
Enable users to change "background-position-x" property for image via YAML header

### ISSUE THREAD

**Issue by melaniewalsh** [minicomp/wax#163]
Our front page banner image looked fine on desktop computers but wonky on mobile, so we wanted to change the "background-position-x" property on the banner image in addition to the "background-position-y" property. It seems like it would be useful to allow Wax users to change this property in the YAML header with an "x" option. 

I believe the x property would be [added here in parallax_image.html](https://github.com/minicomp/wax/blob/69f27b8fa86e7ccc337c2f2f8f86c6b5bb30340d/_includes/parallax_image.html#L10C24-L10C26).

More ambitiously, it would be interesting to add styling possibilities that are separate for desktop and mobile.

**Comment by mnyrop** [comment]
@melaniewalsh closing this for now in favor of Slack conversation; I can reopen it if needed!
