### ISSUE TITLE
lunr index generation needs attention

### ISSUE THREAD

**Issue by elotroalex** [minicomp/wax#36]
it seems that the file is being placed in the /js/ folder and mislabeled as `lunr-index.json` when the `lunr-ui.js` wants it to be root and labeled `search-index.json`.

**Comment by mnyrop** [comment]
I've been playing around with where the lunr files should be generated by default and how much control users should have about that. I'm open to thoughts, but am at the moment refactoring the lunr task within wax_tasks to have the UI file use liquid so it can find the appropriate index dynamically by referencing the site's _config.

**Comment by mnyrop** [comment]
I also think the UI should show '0 results' when typing by default, so it doesn't look like the search isn't working when in fact there are just no results. 

I just created another issue #37 for UI updates. @elotroalex: can you add ideas / issues to it and I'll turn them into action items?

**Comment by mnyrop** [comment]
(Closing in favor of issue #37)
