### ISSUE TITLE
derivatives:simple aborts when smaller than 1140 width image used 

### ISSUE THREAD

**Issue by blros** [minicomp/wax#53]
Some of my original images are not so big and I get the following error running derivatives:simple

rake aborted!
WaxTasks::Error::InvalidConfig: Requested variant width '1140' is larger than original image width.

**Comment by mnyrop** [comment]
As it stands, this is currently intended behavior. Is there a use case where you think it should not be?
Also: is there is a public repository you're working on that I can look at?

**Comment by blros** [comment]
Just poking around on it locally at the moment with different collections, no public repository at this point. 

One of the collections I'm working with  a lot of smaller images, some not so great quality, widths range from 1100 down to 200 in some cases (where only a thumb was available). It's a legacy collection gathered from older websites, no chance to make new hi-res images. But I still want to make them available online as part of a collection, and i don't see a way to do that with the current scripts. In these cases, can those original file sizes be used as the "full" image?

**Comment by mnyrop** [comment]
How big is the collection (# of items)? 

In your case, it might make sense to skip the `derivatives` task entirely. You could just add the `full` and `thumb` columns yourself with paths to the images you have.  The only issue is that you would need to avoid using the banners on the site, since they'd look stretched/pixelated.

**Comment by mnyrop** [comment]
Also, in a future release I'm planning on allowing users to override the derivative sizes they request via `_config.yml`. This seems like it could be a use case for that feature.

**Comment by blros** [comment]
I'm just trying to learn Wax by testing it out on a handful of images at the moment. But the full collection, if we ever go forward with it, is 10,000+ images, and probably makes more sense as you say to make my own derivatives. (Related question: how would Wax fare with a collection that size?)

I like the idea of putting the overide option in _config.yml. In either case, might be good to note this width limitation in the Preparing Your Data section of the documentation.

**Comment by blros** [comment]
And thanks for your help and for creating Wax in general!

**Comment by mnyrop** [comment]
Good point on the documentation in the meantime. I'll add an issue to the Wiki.
About the large collections: it really just depends on the size of the images, whether or not you're using IIIF, and how long you're willing to wait for the task to run. Once it's processed and online it should be fine, though there are some circumstantial caveats for storage and search.

As an example, https://bunraku.library.columbia.edu/ is a Wax site with adapted Columbia styling that has 10s of thousands of pages. Works well enough.
