### ISSUE TITLE
leading backslash is missing at start simple image paths

### ISSUE THREAD

**Issue by blros** [minicomp/wax#54]
When generating simple images, the new paths that are added to the original data file (for both the thumbnail and full) seem to be missing leading backslashes, causing the images not to display on the built site.

**Comment by mnyrop** [comment]
Usually this is handled/normalized by jekyll with the liquid filter `| absolute_url`. Are you using the Wax theme? If there is a public repo I'd be happy to take a look.

**Comment by blros** [comment]
Sorry, I'm currently just testing it out on a a couple of platforms locally, no public repo at this point.

I'm using the Wax theme. Some more info:

derivatives:iiif works fine and places the leading slash, but derivatives:simple does not. You can see the difference below. I'm not changing anything else in the _config or any other file. 

After I run derivatives:iiif the first line of the rewritten csv file looks like:

pid,category,label,order,layout,collection,thumbnail,full,manifest
55865,Roman Republic Coins," L. Marcius Philippus. 56 BC. Silver Denarius (4.05g) . Head of Ancus Marcius right, lituus behind, ANCVS below/Equestrian statue on Aqueduct (the Aqua Macia), PHILIPPVS on left. Marcia-28-29, SR-382. Toned F-VF, bit off-center. ",01,coins_item,coins,"/img/derivatives/iiif/images/55865/full/250,/0/default.jpg",/img/derivatives/iiif/images/55865/full/full/0/default.jpg,/img/derivatives/iiif/55865/manifest.json

After I run derivatives:simple the first line looks like:

```
pid,category,label,order,layout,collection,thumbnail,full
55865,Roman Republic Coins," L. Marcius Philippus. 56 BC. Silver Denarius (4.05g) . Head of Ancus Marcius right, lituus behind, ANCVS below/Equestrian statue on Aqueduct (the Aqua Macia), PHILIPPVS on left. Marcia-28-29, SR-382. Toned F-VF, bit off-center. ",01,coins_item,coins,img/derivatives/simple/55865/thumbnail.jpg,img/derivatives/simple/55865/full.jpg
```
When I build the website w/iiif images, the URLs for the images are wax/img/derivatives (works fine)
When I build the website w/ simple images, the URLs for the images are waximg/derivatives/etc (no slash and thus no image found)

**Comment by mnyrop** [comment]
I'm getting the slash when I run it, so if you're not it definitely seems like a bug. 
One guess: are you using a `baseurl` in your `config`?

**Comment by blros** [comment]
Yes, using baseurl as it shipped in the default collection: '/wax'

**Comment by mnyrop** [comment]
Moving to https://github.com/minicomp/wax_tasks/issues/35
