### ISSUE TITLE
WaxTasks::Error:MissingPID

### ISSUE THREAD

**Issue by profkatemcd** [minicomp/wax#65]
Hi All,

I'm trying to run the tasks with my own small collection of images. I keep running into this error: WaxTasks::Error::MissingPid: Collection is missing pid for item 0. I've checked the CSV file and folder within raw_images for obvious errors (formatting matches the example, etc). I can't figure it out. Any thoughts?

Thanks.

wax-master kate$ bundle exec rake wax:derivatives:iiif vinsel
rake aborted!
WaxTasks::Error::MissingPid: Collection is missing pid for item 0.
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/utils.rb:30:in `block in assert_pids'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/utils.rb:30:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/utils.rb:30:in `each_with_index'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/utils.rb:30:in `assert_pids'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/utils.rb:20:in `ingest'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/collection/metadata.rb:39:in `records_from_metadata'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/collection/images.rb:27:in `items_from_imagedata'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/collection/images.rb:117:in `write_iiif_derivatives'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/site.rb:59:in `generate_derivatives'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/tasks/derivatives_iiif.rake:13:in `block (4 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/tasks/derivatives_iiif.rake:13:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/tasks/derivatives_iiif.rake:13:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/kate/.gem/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/Users/kate/.gem/ruby/2.6.0/bin/bundle:23:in `load'
/Users/kate/.gem/ruby/2.6.0/bin/bundle:23:in `<main>'
Tasks: TOP => wax:derivatives:iiif
(See full trace by running task with --trace)
128-111-61-45:wax-master kate$

**Comment by mnyrop** [comment]
Hi!

You can find more info on structuring your metadata file here: https://minicomp.github.io/wiki/wax/preparing-your-collection-data/metadata/

Basically, every record needs a unique `pid` value (i.e., a  persistent identifier). That error is thrown when one or more records do not have a `pid`. If you have your CSV online somewhere feel free to comment with a link and I can try and take a look.

**Comment by profkatemcd** [comment]
Hi Marii,

Thanks for following up. I thought I did the metadata CSV correctly. Please let me know if you see something that I missed. PDF of the CSV attached here.
[vinsel.pdf](https://github.com/minicomp/wax/files/3399275/vinsel.pdf)

Best,
Kate

**Comment by mnyrop** [comment]
Hi Kate, it does look correct, though it's hard to tell via PDF. Is there a chance I could look at the csv itself? Even better, could I see the whole site repository/project you're working on? Regardless, thanks for your time and willingness to try this stuff out!

**Comment by profkatemcd** [comment]
Hi Marii,

Sure. I couldn't upload the CSV to Github, but I'll attach it here.

Thanks for the help -- I'm excited to use the theme!

Kate


**********************************
Kate McDonald
Associate Professor

Department of History (HSSB 4001)
University of California, Santa Barbara
Santa Barbara, CA 93106-9410

Now available online: *Bodies and Structures 1.0: Deep-Mapping Modern East
Asian History <http://scalar.chass.ncsu.edu/bodies-and-structures>*
Now available online: *People-Works: The Labor of Transport
<http://t2m.org/publications/people-works-the-labor-of-transport> *(an
online exhibit)
Now available from UC Press: *Placing Empire: Travel and the Social
Imagination in Imperial Japan*
<http://www.ucpress.edu/book.php?isbn=9780520293915&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+ucpress%2Fhistory+(UC+Press+-+History+New+Titles)&utm_content=FeedBurner>
(2017)

**Comment by profkatemcd** [comment]
I'm excited to use the theme. I've just uploaded the repository and added you as a collaborator. Please take a look and let me know what you see. Thanks!

**Comment by mnyrop** [comment]
Hi Kate,

I think I found the problem: https://csvlint.io/validation/5d373f21c4a11e0004000063
Some rows in the CSV have fewer columns than others, so the fields are getting scrambled a bit. A few extra commas (to designate empty fields) should fix it, though there are also unescaped quotation marks that could pose a problem later.

How did you create/export the CSV file? Making a spreadsheet in Google sheets and then exporting as CSV is the method I would recommend.

**Comment by mnyrop** [comment]
For example, there are more columns in the first row (as separated by commas) than there are headers, so it doesn't know what to do with the values.

If there's a literal comma in one of your cells, then the whole cell needs to be in quotes. Exporting from Google Sheets or Numbers will do this for you, though I would *strongly* advise against Excel. 

Closing this issue for now, but still happy to chat about it.
