### ISSUE TITLE
Thumbnails not showing on multipage

### ISSUE THREAD

**Issue by jm-chris** [minicomp/wax#66]
Hi Marii and Alex,

Thanks so much for developing Wax. I set up a gh-pages site using the Wax demo for a collection of multi-page documents (five separate documents, each document 9-30 images). My raw images are in five folders, and the images in each of the folders are jpegs. Here's a link to the repository: 

Repo: https://github.com/jm-chris/grassroots_september/tree/gh-pages
Site: https://jm-chris.github.io/grassroots_september/

After I run the tasks for iiif derivatives, the site builds just fine, but I run into two issues with the thumbnails on the 'collection_item' pages. First, the actual images for each of the thumbnails don't seem to display. There is a kind of greyed-out placeholder button where a thumbnail should be that still lets you click forward to the next image, but the thumbnail itself isn't there, and I am not sure if it was ever produced. When I run the iiif derivatives task, I do get a repeating error message in the terminal (pasted at the bottom here) but I'm not sure if it's related.

Second, for the 'shadow thumbnails' and the derivatives that do output to the site, they don't seem to hold to any particular order with regard to the original sequencing in my raw images/collection directory. Within my raw images/collection directory, my folder was named doc1 (same as the pid in the .csv), and then the jpegs inside were named either 00.jpeg, 01.jpeg, 02.jpeg... OR alternately aa.jpeg ab.jpeg, ac.jpeg...and so on. I tried both numerical and alphabetic naming conventions separately and ran the tasks for each, but in each case, running the iiif derivatives tasks would scramble the order of the images on the site, so image 01.jpeg would be followed by 05.jpeg, or 29.jpeg, in seemingly random fashion.

Any ideas on what might be happening? Is this a Wax thing or an ImageMagick thing? Any ideas or suggestions would be greatly appreciated!

Here's what I'm running:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
Bundler version 2.0.2
jekyll 3.8.6
Version: ImageMagick 7.0.8-56 Q16 x86_64 2019-07-24
GPL Ghostscript 9.27 (2019-04-04)

Error message from Terminal when running iiif derivatives task:

[###########                                            ] [1/5] [ 20.00%] [02:36] [10:27] [0.01/s]mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-1jouj5i.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-6uvpyf.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-16ww8fv.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-1wha3ex.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-10n0drv.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-191bfum.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-si5esh.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-110qwcm.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-1bjmejw.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-1o38a6a.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-1wdywaw.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-qigmhu.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-kee7nr.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-p9htrn.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-zljj35.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-1xdor24.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-13rr5se.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-1gi99ai.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-13pr2y5.jpeg' @ warning/transform.c/CropImage/643.
[############################################           ] [4/5] [ 80.00%] [13:15] [03:18] [0.01/s]mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-yud0wd.jpeg' @ warning/transform.c/CropImage/643.
mogrify: geometry does not contain image `/var/folders/j4/sxkdk57d3z9gmz9ck06f4_y40000gn/T/mini_magick20190815-1383-1un8p5m.jpeg' @ warning/transform.c/CropImage/643.

**Comment by mnyrop** [comment]
@jm-chris let me take a look! I might have some follow up questions but I'll try to reproduce the error first.

**Comment by mnyrop** [comment]
Hi @jm-chris, I did some poking around and there's a few things going on.
1. The `mogrify` errors are not related although there's an issue to note here as well. This error is thrown when an original image provided is not as large as one or more derivatives requested; e.g., if image `a` is only 500px wide but Wax want to create an 1140px width access copy for site banners, it will not be able to do so. I wrote custom error messaging to handle this and warn users, but it seems it's not getting triggered for some reason. Tl;dr: this isn't the culprit for the thumbnail problem, but is worth knowing.
2. The thumbnails are being generated correctly (see: [doc2_ab](https://jm-chris.github.io/grassroots_september/img/derivatives/iiif/images/doc2_ab/full/250,/0/default.jpg)) and the IIIF manifests are referencing them correctly (see: [doc2](https://jm-chris.github.io/grassroots_september/img/derivatives/iiif/doc2/manifest.json) line 6), yet the viewer is ignoring the manifest and incorrectly looking for a `256` instead of a `250` width: `https://jm-chris.github.io/grassroots_september/img/derivatives/iiif/images/doc2_ab/full/256,/0/default.jpg`. The viewer is OpenSeadragon, so I'll need to see what the bug is on their end. 

I'll look into the ordering error next–hopefully soon.

**Comment by jm-chris** [comment]
Dear Marii,

Thank you so much for looking into this issue. Obviously it’s not a huge thing and worst comes to worst I believe I could run the tasks on the images compiled as PDF and it might work, but based on my testing the derivatives task would take a lot longer. I was wondering, could it be the large number of images I have in each folder that causes the thumbnail carousel to break? I saw on the Qatar demo site there were always just a handful of images, while all five of my doc folders each have 9-30. 

In any case, since we’ve opened this correspondence, I also wanted to use this opportunity to just thank you for developing Wax. I can’t tell you how long I’ve scoured the interwebs for something just like this, wishing for something like Wax to come along. I never would have guessed that something so perfect would get cooked up right here in my own backyard. I’ve heard great things about you from Alex and I’m beyond grateful that you’ve taken such an active approach to quashing bugs. I’m really looking forward to seeing how you guys take Wax forward and being an active member of the community!

**Comment by mnyrop** [comment]
It definitely might be related...? I'm going to shift focus to fixing the ordering bug first (since that's definitely an issue in wax proper), though in the meantime would you be interested in using another viewer, like [Leaflet-IIIF](https://github.com/mejackreed/Leaflet-IIIF) or [Mirador](https://projectmirador.org/demo/)? Writing "recipes" for swapping in different IIIF viewers is high on my to-do list, and I'd be happy to share such guides once they exist.

And thank you! That's really encouraging to hear, truly. It would be great to stay in contact and hear your ideas going forward.

**Comment by jm-chris** [comment]
Hi @mnyrop,
Just a quick update. I reran the IIIF tasks on PDF raw images (instead of JPEGs in folders) and the thumbnails and sequencing generated exactly as expected. They are working beautifully. I spoke to @elotroalex who says the PDFs were confirmed to work, so that's good. The only downside of doing it this way is that the derivatives created by running tasks on PDFs make the repository very big, to the point where it's no longer possible to push the commit to GitHub. I know you're still looking into the sequencing bug, thanks for the support.
