### ISSUE TITLE
"Rake aborted" when generating derivatives 

### ISSUE THREAD

**Issue by jloan** [minicomp/wax#69]
Very much a novice here...

Following the documentation, when I run the first task the rake aborts and I get this message:

> Generating IIIF derivatives for collection 'zines'
This might take awhile.
rake aborted!
WaxIiif::Error::InvalidImageData: Cannot read this image file: _data/raw_images/zines/zine2.jpg. `identify /var/folders/5t/n99lj6td3_q74h427zhjfc5m0000gn/T/mini_magick20191010-84071-b38gzx.jpg` failed with error:
identify: no decode delegate for this image format `JPG' @ error/constitute.c/ReadImage/560.
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/image_variant.rb:37:in `rescue in initialize'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/image_variant.rb:34:in `initialize'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/builder.rb:233:in `new'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/builder.rb:233:in `generate_variants'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/builder.rb:253:in `block in process_image_records'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/builder.rb:246:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/builder.rb:246:in `process_image_records'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/builder.rb:76:in `block in process_data'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/builder.rb:73:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_iiif-0.1.2/lib/wax_iiif/builder.rb:73:in `process_data'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/collection/images.rb:124:in `write_iiif_derivatives'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/wax_tasks/site.rb:59:in `generate_derivatives'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/tasks/derivatives_iiif.rake:13:in `block (4 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/tasks/derivatives_iiif.rake:13:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/wax_tasks-1.0.2/lib/tasks/derivatives_iiif.rake:13:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/musicforparkinglots/.gem/ruby/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/opt/ruby/bin/bundle:23:in `load'
/usr/local/opt/ruby/bin/bundle:23:in `<main>'

Caused by:
MiniMagick::Invalid: `identify /var/folders/5t/n99lj6td3_q74h427zhjfc5m0000gn/T/mini_magick20191010-84071-b38gzx.jpg` failed with error:
identify: no decode delegate for this image format `JPG' @ error/constitute.c/ReadImage/560.

I can run the site locally, but no images are generated. Any ideas?

**Comment by mnyrop** [comment]
Are you on a Mac? And if so, did you install imagemagick using `brew`? Seems like an imagemagick issue, but it's hard to tell.

Can you tell me what output you get when you run the command `identify -list format` ??

**Comment by jloan** [comment]
Thanks for your response and patience with a novice. I believe I got my original issue ironed out this am. It was a wonky install of imagemagick. I reinstalled -- this time with Homebrew and not from source. When I ran the tasks I received no errors. Yeah!

Unfortunately, I'm not seeing any images at all when I build the site. I can search for items and do get results, but when I go to the item there is no image, just a "grayed" space. Been digging around to see if there's any settings or config issues, but nothing has jumped out yet...any thoughts?

**Comment by jloan** [comment]
I am on a mac.

**Comment by mnyrop** [comment]
Hi @jloan , do you have a public GitHub repository I can look at?

My guess is that you need to regenerate the pages. When you run the `derivatives` task, it generates the images *and* adds the image paths to your CSV or other data file. Then the `pages` task creates markdown pages from that data file. If you run `pages` before you successfully run `derivatives` those pages won't know about the images created. Does that make sense? It's hard to explain in writing, but basically the task order is important. See: https://minicomp.github.io/wiki/wax/running-the-tasks/

If you've already run the `pages` task, I'd just delete the folder of pages it generated (probably `_zines` in your case) and run it again.

**Comment by mnyrop** [comment]
Closing this issue, but happy to keep chatting about it.
