### ISSUE TITLE
First image request sometimes does not load

### ISSUE THREAD

**Issue by awoods** [minicomp/wax#74]
Although not every time, with a fair degree of regularity, when I come to our site (and even to https://minicomp.github.io/wax/) the first image I click in the gallery navigates to the item viewer... but the viewer is blank.

If I reload the page, the image appears in the viewer. Subsequent clicks on the same and other images result in the expected, correct loading behavior.

It seems that possibly the openseadragon viewer loads before the image... resulting in an empty viewer.

Possibly not critical, but it is a non-optimal user experience when the first image they select does not load.

**Comment by mnyrop** [comment]
This is still a bug, but as an update @pbinkley has been looking into similar issues here: https://github.com/pbinkley/postwax

**Comment by mnyrop** [comment]
@awoods i \*believe\* this has been fixed on https://minicomp.github.io/wax/ by @bmschmidt 's commit removing `async` from  the openseadragon script tag. if you get the chance, can you let me know if removing `async` works for your use case(s) as well? i can't tell if it's incidental

https://github.com/minicomp/wax/commit/1353f3067edc1361d2530875b93b323196893412

**Comment by mnyrop** [comment]
(closing but can reopen.)

**Comment by awoods** [comment]
I will test and get back with you.

**Comment by awoods** [comment]
So far so good on this fix on our production site: https://history.lakecountypubliclibrary.org/

**Comment by mnyrop** [comment]
thanks @awoods !

i also wanted to thank you again for your docker work. alex and I ended up using a slightly revised version for a remote wax workshop last week where managing installs was too scary to consider. it was really nice to have!

**Comment by awoods** [comment]
This issue does indeed appear to have been resolved. Thanks!
