### ISSUE TITLE
IIIF Image Server?

### ISSUE THREAD

**Issue by karinanw** [minicomp/wax#9]
Hi, silly question. Does this repository assume Amazon S3 (as CMOA IIIFS3 does)?

**Comment by mnyrop** [comment]
Hi Karina, 

Nope! It completely scraps the s3 part of IIIF_s3. Documentation is forthcoming, but if you try it as-is, your IIIF derivatives will be generated locally to ./iiif/{{ your-collection-name }} in the root of your site.
