### ISSUE TITLE
Reduce size of images in the template

### ISSUE THREAD

**Issue by brimwats** [minicomp/wax#96]
We're sorry, something went wrong.
We were unable to clone minicomp/wax's contents into [...] The template you used includes files that are larger than 10 megabytes. Please ask minicomp to remove those files from the template and try again.

**Comment by mnyrop** [comment]
@brimwats a patch for this is in the works. as a sneak peek, the new version of the repo will load the source data from a git submodule so it's not in the demo/theme repo: https://github.com/minicomp/wax/tree/data-from-submodule

does this seem like it would work for your use case(s)?

**Comment by mnyrop** [comment]
I still want to pull the original source images into a submodule at some point, but "use this template" seems to be working on GitHub's end now. Closing this issue.
