### ISSUE TITLE
Add Chocolatey Instructions to Documentation

### ISSUE THREAD

**Issue by brimwats** [minicomp/wax#97]
I wrote these up for a workshop that @egrguric ran for @ubc-library 

Numbers 1 and 2 come from chocolatey's page:

1. Run `Get-ExecutionPolicy.` If it returns **Restricted**, then run `Set-ExecutionPolicy AllSigned` or `Set-ExecutionPolicy Bypass -Scope Process`

2. Run

```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

```

3. Close then reopen the terminal # might not be needed but just to be safe

4. Run

choco install ruby imagemagick ghostscript 

5. Run

gem install jekyll bundler

**Comment by mnyrop** [comment]
@brimwats nice! is it okay if I close the issue (since it's not an issue per se) but folks will still be able to find it when searching issues? or is this a proposal for a docs change in the wiki?

**Comment by brimwats** [comment]
Sure! It was a proposal for you to add it to the wiki, but I don't know how to do that—so feel free to close if easier!

BRIAN M. WATSON
They/m<http://pronoun.is/they/.../themself> - Twitter<https://twitter.com/brimwats> - Website<https://brimwats.com/>
Director: HistSex.org<https://histsex.com/> | Editorial Board: Homosaurus<http://homosaurus.org/about>
Archivist-Historian: APA Division 44 CNM Taskforce<https://www.apadivisions.org/division-44/leadership/task-forces/>
PhD: University of British Columbia School of Information<https://ischool.ubc.ca/>, Musqueam Traditional Territory

------ Original Message ------
